name: Vue

on:
  schedule:
    - cron: '30 7 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  vue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout repo
        run: git submodule update --init repos/${{ github.job }}
      - name: Pull latest repo
        run: git submodule update --remote repos/${{ github.job }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Execute GitStats
        run: bundle exec git_stats generate -p repos/${{ github.job }} -o docs/git_stats/${{ github.job }} --silent
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic update of ${{ github.job }} repository statistics
          commit_author: GitHub Actions <actions@github.com>
          file_pattern: docs/* repos/${{ github.job }}
