name: Vue

on:
  schedule:
    - cron: '30 7 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  vue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Add repo if not exists
        run: if [ ! -d repos/${{ github.job }} ]; then git submodule add https://github.com/vuejs/vue.git repos/${{ github.job }}; fi;
      - name: Checkout repo
        run: git submodule update --init repos/${{ github.job }}
      - name: Pull latest repo
        run: git submodule update --remote repos/${{ github.job }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Execute GitStats
        run: bundle exec git_stats generate -p repos/${{ github.job }} -o docs/${{ github.job }} --silent
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Automatic update of ${{ github.job }} repository statistics
          commit_author: GitHub Actions <actions@github.com>
          file_pattern: docs/* repos/${{ github.job }}
